server:
  port: 8080

spring:
  application:
    name: zero-to-tech-server

  # 默认激活本地开发环境配置 (dev)
  profiles:
    active: dev

  # 数据源驱动与建表脚本规则
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

  # Spring AI 通用参数
  ai:
    openai:
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-flash
          temperature: 0.3

# MyBatis-Plus 全局基础配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
